### ISSUE TITLE
React way of pagination?

### ISSUE THREAD

**Issue by teodorpenkov** [apollographql/apollo-ios-pagination#9]
I've seen several comments in the apollo-ios repo about an Initial query and merging subsequent queries' data into the first one (similar to the react way of pagination) in order to perform pagination.

Is this an option in Apollo iOS? If not - why not?

**Comment by BobaFetters** [comment]
Moved this issue to the `apollo-ios` repo as that is where we handle all issues related to apollo-ios https://github.com/apollographql/apollo-ios/issues/3255
